In [9]:
import pandas as pd
import numpy as np

csv_femlit = "Resources/female_literacy.csv"
csv_malelit = "Resources/male_literacy.csv"
csv_fertility_rate = "Resources/fertility rate.csv"


# Labor force participation rate, female (% of female population ages 15+) 
female_lit = pd.read_csv(csv_femlit)
malelit = pd.read_csv(csv_malelit)
fertility_rate = pd.read_csv(csv_fertility_rate)
fertility_rate.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.820,4.655,4.471,4.271,4.059,3.842,...,1.764,1.769,1.776,1.783,1.791,1.796,1.800,1.801,1.800,NaN
1,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.450,7.450,7.450,7.450,7.450,7.450,...,6.254,6.038,5.816,5.595,5.380,5.174,4.981,4.802,4.635,NaN
2,Angola,AGO,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.478,7.524,7.563,7.592,7.611,7.619,...,6.307,6.238,6.162,6.082,6.000,5.920,5.841,5.766,5.694,NaN
3,Albania,ALB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.489,6.401,6.282,6.133,5.960,5.773,...,1.650,1.646,1.653,1.668,1.685,1.700,1.710,1.714,1.713,NaN
4,Andorra,AND,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.250,1.190,1.270,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
merged_df = pd.merge(female_lit, malelit, how='inner', on=['Country Code'], suffixes=('_flit', '_mlit'))
# merged_df_clean = merged_df.loc[:, )
merged_df = merged_df.dropna(how='all', axis=1)
# merged_df = merged_df.dropna(how='all', axis=0)
# merged_df.index = merged_df['Country Code']
merged_df = merged_df[['Country Code', 'Country Name_flit', '1970_flit', '1972_flit', '1973_flit',
       '1974_flit', '1975_flit', '1976_flit', '1977_flit', '1978_flit',
       '1979_flit', '1980_flit', '1981_flit', '1982_flit', '1983_flit',
       '1984_flit', '1985_flit', '1986_flit', '1987_flit', '1988_flit',
       '1989_flit', '1990_flit', '1991_flit', '1992_flit', '1993_flit',
       '1994_flit', '1995_flit', '1996_flit', '1997_flit', '1998_flit',
       '1999_flit', '2000_flit', '2001_flit', '2002_flit', '2003_flit',
       '2004_flit', '2005_flit', '2006_flit', '2007_flit', '2008_flit',
       '2009_flit', '2010_flit', '2011_flit', '2012_flit', '2013_flit',
       '2014_flit', '2015_flit', '2016_flit', '1970_mlit', '1971_mlit',
       '1972_mlit', '1973_mlit', '1974_mlit', '1975_mlit', '1976_mlit',
       '1977_mlit', '1978_mlit', '1979_mlit', '1980_mlit', '1981_mlit',
       '1982_mlit', '1983_mlit', '1984_mlit', '1985_mlit', '1986_mlit',
       '1987_mlit', '1988_mlit', '1989_mlit', '1990_mlit', '1991_mlit',
       '1992_mlit', '1993_mlit', '1994_mlit', '1995_mlit', '1996_mlit',
       '1997_mlit', '1998_mlit', '1999_mlit', '2000_mlit', '2001_mlit',
       '2002_mlit', '2003_mlit', '2004_mlit', '2005_mlit', '2006_mlit',
       '2007_mlit', '2008_mlit', '2009_mlit', '2010_mlit', '2011_mlit',
       '2012_mlit', '2013_mlit', '2014_mlit', '2015_mlit', '2016_mlit']]

merged_df = merged_df.rename(columns={'Country Name_flit': 'Country Name'})
# merged_df.columns


merged_df.to_csv('merged_data.csv')
merged_df

,Country Code,Country Name,1970_flit,1972_flit,1973_flit,1974_flit,1975_flit,1976_flit,1977_flit,1978_flit,...,2007_mlit,2008_mlit,2009_mlit,2010_mlit,2011_mlit,2012_mlit,2013_mlit,2014_mlit,2015_mlit,2016_mlit
0,ABW,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,96.940529,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,45.417099,NaN,NaN,NaN,NaN,NaN
2,AGO,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.974152,NaN,NaN
3,ALB,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,97.306198,NaN,NaN,98.008163,98.352608,NaN,NaN,NaN,NaN
4,AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,100.000000
5,ARB,Arab World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.01895,...,78.263120,78.725960,77.563620,78.147710,79.498590,80.389140,80.708310,81.042340,81.334830,81.582860
6,ARE,United Arab Emirates,NaN,NaN,NaN,NaN,38.124870,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ARG,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.040001,NaN
8,ARM,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,99.806084,NaN,NaN,NaN,NaN,NaN
9,ASM,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ATG,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,AUS,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,AUT,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AZE,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99.823998,NaN,99.842667,99.854439,99.856659,99.852852,99.865921,99.862007,99.862633,99.864052
14,BDI,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,53.128391,NaN,NaN,NaN,NaN,NaN,69.692513,NaN,NaN
15,BEL,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,BEN,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,44.960258,NaN,NaN,NaN,NaN
17,BFA,Burkina Faso,NaN,NaN,NaN,NaN,3.182770,NaN,NaN,NaN,...,36.680672,NaN,NaN,NaN,NaN,NaN,NaN,44.379452,NaN,NaN
18,BGD,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.832329,NaN,NaN,NaN,47.449848,NaN,NaN,NaN,NaN,75.618851
19,BGR,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,98.747231,NaN,NaN,NaN,NaN,NaN
20,BHR,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,96.140228,NaN,NaN,NaN,NaN,NaN,NaN
21,BHS,"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,BIH,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,99.541328,NaN,99.176277,NaN,NaN,NaN
23,BLR,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,99.763687,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,BLZ,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,BMU,Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,BOL,Bolivia,NaN,NaN,NaN,NaN,NaN,51.374649,NaN,NaN,...,96.036263,94.955429,95.803642,NaN,96.601051,97.107048,NaN,NaN,96.522751,NaN
27,BRA,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.772141,89.837868,90.174843,90.056183,91.168983,91.025673,91.177963,91.366768,NaN,NaN
28,BRB,Barbados,99.251556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,BRN,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,97.428162,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,TLA,Latin America & the Caribbean (IDA & IBRD coun...,NaN,NaN,NaN,75.18452,75.187020,75.631120,76.16588,76.73601,...,91.519170,91.830340,92.067160,92.040870,92.639490,92.803880,92.820530,93.221000,93.602560,93.882890
235,TLS,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,58.500000,NaN,NaN,63.591789,NaN,NaN,NaN,NaN,NaN,NaN
236,TMN,Middle East & North Africa (IDA & IBRD countries),NaN,24.34333,24.84588,25.36251,25.924600,26.748230,27.14884,27.91739,...,81.300930,81.663680,81.032520,81.517610,81.660980,82.265070,82.592610,82.872610,83.390070,83.685180
237,TON,Tonga,NaN,NaN,NaN,NaN,NaN,99.525528,NaN,NaN,...,NaN,NaN,NaN,NaN,99.335098,NaN,NaN,NaN,NaN,NaN
238,TSA,South Asia (IDA & IBRD),NaN,NaN,NaN,NaN,21.379570,21.387920,22.12109,22.86941,...,73.134180,74.588470,75.111460,75.552730,74.470330,77.606210,77.949990,78.451690,78.926540,79.367550
239,TSS,Sub-Saharan Africa (IDA & IBRD countries),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.166310,66.469680,67.752930,67.931620,69.099500,70.060900,70.401400,70.967260,71.285170,71.726210
240,TTO,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,TUN,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.053680,86.375809,NaN,87.375732,87.760757,88.475777,NaN,86.060120,NaN,NaN
242,TUR,Turkey,NaN,NaN,NaN,NaN,45.098919,NaN,NaN,NaN,...,96.201859,NaN,96.377708,97.299812,97.934990,98.262901,98.401367,98.496788,98.575623,NaN
243,TUV,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,TZA,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,75.467796,NaN,83.377693,NaN,NaN,83.204849,NaN
245,UGA,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,82.631393,NaN,79.123039,NaN,NaN,NaN,NaN
246,UKR,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,99.993942,NaN,NaN,NaN,NaN
247,UMC,Upper middle income,NaN,NaN,NaN,NaN,NaN,59.465180,59.55141,60.54583,...,95.662520,95.824280,95.803560,95.823560,96.021880,96.104520,96.145280,96.271090,96.417300,96.529220
248,URY,Uruguay,NaN,NaN,NaN,NaN,94.304520,NaN,NaN,NaN,...,97.421692,97.831284,97.972420,97.610168,98.023109,98.103973,98.063423,98.025070,98.145920,NaN
249,USA,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,UZB,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,99.993828,99.985191,99.992043,NaN
251,VCT,St. Vincent and the Grenadines,95.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,VEN,"Venezuela, RB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.381729,NaN,95.675369,NaN,94.502319,NaN,NaN,NaN,96.651077,97.039108
253,VGB,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,VIR,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,VNM,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,95.785332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,VUT,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,WLD,World,NaN,NaN,NaN,NaN,NaN,61.037970,61.14919,61.62464,...,88.061500,88.343910,88.557430,88.644630,88.460420,89.282400,89.357960,89.554340,89.706900,89.837720
258,WSM,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,98.881920,NaN,NaN,NaN,NaN,NaN
259,XKX,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,YEM,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,ZAF,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.717590,NaN,94.121460,94.143852,94.245087,94.963722,NaN,95.286850,95.396530,NaN
262,ZMB,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.947441,NaN,NaN,88.684029,NaN,NaN,NaN,NaN,NaN,NaN
263,ZWE,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,87.764809,NaN,NaN,89.185371,NaN,NaN