In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from scipy.stats import pearsonr
import numpy as np

In [3]:
labor_all_csv = 'David_Labor/lab_ratio.csv'
labor_all = pd.read_csv(literacy_all_csv)

mort_all_csv = 'Resources/mortality_under5.csv'
mort_all = pd.read_csv(mort_all_csv)

lit_all_csv = 'Resources/lit_ratio.csv'
lit_all = pd.read_csv(lit_all_csv)

mort_all = mort_all.set_index("Country Code")
labor_all = labor_all.set_index("Country Code")
lit_all = lit_all.set_index("Country Code")

mort_all

NameError: name 'literacy_all_csv' is not defined

In [166]:
mort2017 = mort_all.iloc[:,29]

mort2017

Country Code
ABW      NaN
AFG     67.9
AGO     81.1
ALB      8.8
AND      3.3
ARE      9.1
ARG     10.4
ARM     12.6
ASM      NaN
ATG      7.4
AUS      3.5
AUT      3.6
AZE     23.0
BDI     61.2
BEL      3.8
BEN     98.3
BFA     81.2
BGD     32.4
BGR      7.5
BHR      7.3
BHS      7.2
BIH      5.7
BLR      3.7
BLZ     14.2
BMU      NaN
BOL     34.9
BRA     14.8
BRB     12.4
BRN     10.5
BTN     30.8
       ...
SYR     17.0
TCA      NaN
TCD    123.2
TGO     72.9
THA      9.5
TJK     33.6
TKM     47.3
TON     16.0
TTO     26.1
TUN     13.0
TUR     11.6
TUV     24.9
TZA     54.0
UGA     49.0
UKR      8.8
URY      8.2
USA      6.6
UZB     22.5
VCT     16.2
VEN     30.9
VGB      NaN
VIR      NaN
VNM     20.9
VUT     26.9
WLD     39.1
WSM     16.5
YEM     55.4
ZAF     37.1
ZMB     60.0
ZWE     50.3
Name: 2017, Length: 205, dtype: float64

In [167]:
labor2017 = labor_all.iloc[:,27]

In [168]:
#labor2017

In [169]:
litmean = lit_all.iloc[:,0]

In [170]:
#merge_table = pd.merge(litmean, labor2017, on="Country Code")

In [171]:
print(type(litmean))

<class 'pandas.core.series.Series'>

In [172]:
df_mort2017 = mort2017.to_frame().reset_index()
df_labor2017 = labor2017.to_frame().reset_index()
df_litmean = litmean.to_frame().reset_index()

In [176]:
#df_mort2017

In [174]:
merge_table = pd.merge(df_mort2017, df_labor2017, on="Country Code", how="left")

In [177]:
#merge_table
#x - mort, labor - 4

In [180]:
merge_final = pd.merge(df_litmean, merge_table, on="Country Code", how="left")
merge_final

    Country Code  Ratio of Female to Male Literacy Rates  2017_x    2017_y
0            ABW                                0.996469     NaN       NaN
1            AFG                                0.387785    67.9  0.224571
2            AGO                                0.660563    81.1  0.940468
3            ALB                                0.979400     8.8  0.727965
4            AND                                1.000000     3.3       NaN
5            ARE                                1.022269     9.1  0.444782
6            ARG                                0.999692    10.4  0.646250
7            ARM                                0.996857    12.6  0.728758
8            ASM                                     NaN     NaN       NaN
9            ATG                                1.010366     7.4       NaN
10           AUS                                     NaN     3.5  0.839596
11           AUT                                     NaN     3.6  0.832427
12           AZE                                0.997065    23.0  0.905438
13           BDI                                0.745025    61.2  1.035647
14           BEL                                     NaN     3.8  0.813919
15           BEN                                0.463826    98.3  0.939173
16           BFA                                0.534923    81.2  0.773687
17           BGD                                0.837455    32.4  0.413961
18           BGR                                0.990919     7.5  0.802156
19           BHR                                0.922669     7.3  0.506440
20           BHS                                     NaN     7.2  0.853346
21           BIH                                0.933961     5.7  0.599557
22           BLR                                0.996782     3.7  0.826921
23           BLZ                                1.000849    14.2  0.655249
24           BMU                                     NaN     NaN       NaN
25           BOL                                0.898322    34.9  0.690598
26           BRA                                1.005275    14.8  0.711864
27           BRB                                     NaN    12.4  0.888824
28           BRN                                0.937707    10.5  0.790341
29           BTN                                0.661554    30.8  0.781340
..           ...                                     ...     ...       ...
174          SYC                                1.012535    14.2       NaN
175          SYR                                0.827058    17.0  0.169202
176          TCA                                     NaN     NaN       NaN
177          TCD                                0.374964   123.2  0.834930
178          TGO                                0.624258    72.9  0.955537
179          THA                                0.968683     9.5  0.782709
180          TJK                                0.995358    33.6  0.620500
181          TKM                                0.989296    47.3  0.682183
182          TON                                1.001243    16.0  0.608813
183          TTO                                0.976043    26.1  0.692486
184          TUN                                0.812608    13.0  0.343708
185          TUR                                0.882755    11.6  0.449919
186          TUV                                     NaN    24.9       NaN
187          TZA                                0.842936    54.0  0.909382
188          UGA                                0.750368    49.0  0.888763
189          UKR                                0.996958     8.8  0.745150
190          URY                                1.007249     8.2  0.753997
191          USA                                     NaN     6.6  0.816415
192          UZB                                0.997371    22.5  0.690915
193          VCT                                     NaN    16.2  0.730184
194          VEN                                0.996417    30.9  0.648778
195          VGB                                     NaN     NaN       NaN
196          VIR                                     NaN     NaN  0.884889
197          VNM                                0.933975    20.9  0.877453
198          VUT                                     NaN    26.9  0.772998
199          WSM                                0.995913    16.5  0.610857
200          YEM                                0.300743    55.4  0.086140
201          ZAF                                0.972572    37.1  0.771555
202          ZMB                                0.789420    60.0  0.880370
203          ZWE                                0.928616    50.3  0.881365

[204 rows x 4 columns]

merge_final